/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registromatricula;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */
public class VentanaMatricula extends javax.swing.JFrame {

    ArrayList <Object> listaMaterias = new ArrayList<>();
    ArrayList <Object> listaProfesores = new ArrayList<>();
    ArrayList <Object> listaEstudiantes = new ArrayList <>();
    ArrayList <Object> listaMatricula = new ArrayList<>();
    ClsControlador controlador = new ClsControlador();
    Materia materiaSeleccionada;
    public VentanaMatricula() {
        initComponents(); 
        
        listaMaterias = controlador.extraerObjetos("archivosMaterias.dat");
        llenarComboMateria();
        llenarComboMateriaProfesor();
        llenarComboMateriaFinal();
         if(listaMaterias.size() > 0){
            Materia materia = (Materia) listaMaterias.get(listaMaterias.size()-1);
        } 
       
        listaProfesores = controlador.extraerObjetos("archivosProfesores.dat");
        if(listaProfesores.size() > 0){
            Profesor profesor = (Profesor) listaProfesores.get(listaProfesores.size()-1);
        }
        
        listaEstudiantes = controlador.extraerObjetos("archivosEstudiantes.dat");
        llenarComboEstudiante();
        if(listaEstudiantes.size() > 0){
            Estudiante estudiante = (Estudiante) listaEstudiantes.get(listaEstudiantes.size()-1);
        } 
        
        listaMatricula = controlador.extraerObjetos("archivosMatriculas.dat");
        if(listaMatricula.size() > 0){
            MatriculaEfectuada matricula = (MatriculaEfectuada) listaMatricula.get(listaMatricula.size()-1);
        }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMatricula = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        btnRegistrarMateria = new javax.swing.JButton();
        ComboMateria = new javax.swing.JComboBox<>();
        lblMateriasTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblProfesoresTitulo = new javax.swing.JLabel();
        lblNombreProfesor = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellidoProfesor = new javax.swing.JTextField();
        lblFacultad = new javax.swing.JLabel();
        txtFacultad = new javax.swing.JTextField();
        lblMateriasProfesor = new javax.swing.JLabel();
        ComboMateriasProfesor = new javax.swing.JComboBox<>();
        btnRegistrarProfesor = new javax.swing.JButton();
        lblMensajeProfesor = new javax.swing.JLabel();
        lblEdad = new javax.swing.JPanel();
        lblEstudiantesTitulo = new javax.swing.JLabel();
        lblNombreEstudiante = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        lblApellidoEstudiante = new javax.swing.JLabel();
        txtApellidoEstudiantes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnRegistrarEstudiantes = new javax.swing.JButton();
        lblMensajeEstudiantes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblMatriculaTitulo = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblMaterias = new javax.swing.JLabel();
        ComboEstudiantes = new javax.swing.JComboBox<>();
        ComboMateriasFinal = new javax.swing.JComboBox<>();
        btnRegistrarMatricula = new javax.swing.JButton();
        lblMensajeMatricula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMateria.setText("MATERIA:");

        btnRegistrarMateria.setText("REGISTRAR");
        btnRegistrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMateriaActionPerformed(evt);
            }
        });

        ComboMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAS" }));

        lblMateriasTitulo.setText("REGISTRO DE MATERIAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(ComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMateriasTitulo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMateriasTitulo)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMateria))
                .addGap(45, 45, 45)
                .addComponent(btnRegistrarMateria)
                .addGap(18, 18, 18)
                .addComponent(ComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tabMatricula.addTab("Materias", jPanel1);

        lblProfesoresTitulo.setText("REGISTRO DE PROFESORES");

        lblNombreProfesor.setText("NOMBRE:");

        lblApellido.setText("APELLIDO:");

        lblFacultad.setText("FACULTAD:");

        lblMateriasProfesor.setText("MATERIAS:");

        ComboMateriasProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAS" }));

        btnRegistrarProfesor.setText("REGISTRAR");
        btnRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreProfesor)
                            .addComponent(lblApellido)
                            .addComponent(lblFacultad)
                            .addComponent(lblMateriasProfesor))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComboMateriasProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txtApellidoProfesor)
                            .addComponent(txtFacultad)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblMensajeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 92, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblProfesoresTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnRegistrarProfesor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblProfesoresTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProfesor)
                    .addComponent(txtNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApellido)
                    .addComponent(txtApellidoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultad)
                    .addComponent(txtFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateriasProfesor)
                    .addComponent(ComboMateriasProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnRegistrarProfesor)
                .addGap(375, 375, 375)
                .addComponent(lblMensajeProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        tabMatricula.addTab("Profesores", jPanel2);

        lblEstudiantesTitulo.setText("REGISTRO DE ESTUDIANTES");

        lblNombreEstudiante.setText("NOMBRE:");

        lblApellidoEstudiante.setText("APELLIDO:");

        jLabel3.setText("EDAD:");

        btnRegistrarEstudiantes.setText("REGISTRAR");
        btnRegistrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblEdadLayout = new javax.swing.GroupLayout(lblEdad);
        lblEdad.setLayout(lblEdadLayout);
        lblEdadLayout.setHorizontalGroup(
            lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEdadLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEstudiante)
                    .addComponent(lblApellidoEstudiante)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txtApellidoEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txtNombreEstudiante))
                .addGap(76, 76, 76))
            .addGroup(lblEdadLayout.createSequentialGroup()
                .addGroup(lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblEdadLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblEstudiantesTitulo))
                    .addGroup(lblEdadLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnRegistrarEstudiantes))
                    .addGroup(lblEdadLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblMensajeEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        lblEdadLayout.setVerticalGroup(
            lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblEdadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstudiantesTitulo)
                .addGap(24, 24, 24)
                .addGroup(lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEstudiante)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoEstudiante)
                    .addComponent(txtApellidoEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(lblMensajeEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnRegistrarEstudiantes)
                .addGap(24, 24, 24))
        );

        tabMatricula.addTab("Estudiantes", lblEdad);

        lblMatriculaTitulo.setText("REGISTRO DE MATRICULA");

        lblEstudiante.setText("ESTUDIANTE:");

        lblMaterias.setText("MATERIAS:");

        ComboEstudiantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTES" }));
        ComboEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEstudiantesActionPerformed(evt);
            }
        });

        ComboMateriasFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAS" }));

        btnRegistrarMatricula.setText("REGISTRAR");
        btnRegistrarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaterias)
                            .addComponent(lblEstudiante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboMateriasFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblMensajeMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblMatriculaTitulo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnRegistrarMatricula)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMatriculaTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudiante)
                    .addComponent(ComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaterias)
                    .addComponent(ComboMateriasFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(lblMensajeMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnRegistrarMatricula)
                .addGap(21, 21, 21))
        );

        tabMatricula.addTab("Matricula", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEstudiantesActionPerformed

    private void btnRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfesorActionPerformed
        String nombreP=txtNombreProfesor.getText();
        String apellidoP= txtApellidoProfesor.getText();
        String facultad= txtFacultad.getText();
        Materia materiaSeleccionada = (Materia)ComboMateriasProfesor.getSelectedItem();

        Profesor profesor = new Profesor(nombreP,apellidoP,facultad,materiaSeleccionada);
        listaProfesores.add(profesor);
        controlador.escribirObjeto("archivosProfesores.dat" , listaProfesores);
        listaProfesores = controlador.extraerObjetos("archivosProfesores.dat");
        lblMensajeProfesor.setText("Profesor Registrado");
        
    }//GEN-LAST:event_btnRegistrarProfesorActionPerformed

    private void btnRegistrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMateriaActionPerformed
        System.out.println("registra");

        Materia materias = new Materia(txtMateria.getText());
        listaMaterias.add(materias);
        controlador.escribirObjeto("archivosMaterias.dat", listaMaterias);
        listaMaterias = controlador.extraerObjetos("archivosMaterias.dat");
        llenarComboMateria();
        llenarComboMateriaProfesor();
        llenarComboMateriaFinal();

    }//GEN-LAST:event_btnRegistrarMateriaActionPerformed

    private void btnRegistrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstudiantesActionPerformed
        String nombreE=txtNombreEstudiante.getText();
        String apellidoE= txtApellidoEstudiantes.getText();
        String edad= txtEdad.getText();
    
        Estudiante estudiante = new Estudiante (nombreE,apellidoE,edad);
        listaEstudiantes.add(estudiante);
        controlador.escribirObjeto("archivosEstudiantes.dat" , listaEstudiantes);
        listaEstudiantes = controlador.extraerObjetos("archivosEstudiates.dat");
        lblMensajeEstudiantes.setText("Estudiante Registrado");
        llenarComboEstudiante();
    }//GEN-LAST:event_btnRegistrarEstudiantesActionPerformed

    private void btnRegistrarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMatriculaActionPerformed
        Materia materiaSeleccionada = (Materia)ComboMateriasProfesor.getSelectedItem();
        Estudiante estudianteSeleccionado = (Estudiante) ComboEstudiantes.getSelectedItem();
        MatriculaEfectuada matricula = new MatriculaEfectuada (estudianteSeleccionado,materiaSeleccionada);
        listaMatricula.add(matricula);
        controlador.escribirObjeto("archivosMatriculas.dat" , listaMatricula);
        listaMatricula = controlador.extraerObjetos("archivosMatriculas.dat");
        lblMensajeMatricula.setText("Matricula Registrada");
    }//GEN-LAST:event_btnRegistrarMatriculaActionPerformed
  
    /**
     * @param args the command line arguments
     */
    
    public void llenarComboMateria(){
      if(listaMaterias.size() > 0){
            ComboMateria.setEnabled(true);
            listaMaterias = controlador.extraerObjetos("archivosMaterias.dat");
            ComboMateria.setModel(new javax.swing.DefaultComboBoxModel(listaMaterias.toArray()));
        }else{
            ComboMateria.setEnabled(false);
        }
    } 
    
     public void llenarComboMateriaProfesor(){
      if(listaMaterias.size() > 0){
            ComboMateriasProfesor.setEnabled(true);
            listaMaterias = controlador.extraerObjetos("archivosMaterias.dat");
            ComboMateriasProfesor.setModel(new javax.swing.DefaultComboBoxModel(listaMaterias.toArray()));
        }else{
            ComboMateriasProfesor.setEnabled(false);
        }
    }
     
    public void llenarComboEstudiante(){
      if(listaEstudiantes.size() > 0){
            ComboEstudiantes.setEnabled(true);
            listaEstudiantes = controlador.extraerObjetos("archivosEstudiantes.dat");
            ComboEstudiantes.setModel(new javax.swing.DefaultComboBoxModel(listaEstudiantes.toArray()));
        }
    } 
    
    public void llenarComboMateriaFinal(){
      if(listaMatricula.size() > 0){
            ComboMateriasFinal.setEnabled(true);
            listaMatricula = controlador.extraerObjetos("archivosMatriculas.dat");
            ComboMateriasFinal.setModel(new javax.swing.DefaultComboBoxModel(listaMatricula.toArray()));
        }else{
            ComboMateriasFinal.setEnabled(false);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEstudiantes;
    private javax.swing.JComboBox<String> ComboMateria;
    private javax.swing.JComboBox<String> ComboMateriasFinal;
    private javax.swing.JComboBox<String> ComboMateriasProfesor;
    private javax.swing.JButton btnRegistrarEstudiantes;
    private javax.swing.JButton btnRegistrarMateria;
    private javax.swing.JButton btnRegistrarMatricula;
    private javax.swing.JButton btnRegistrarProfesor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellidoEstudiante;
    private javax.swing.JPanel lblEdad;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblEstudiantesTitulo;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblMateriasProfesor;
    private javax.swing.JLabel lblMateriasTitulo;
    private javax.swing.JLabel lblMatriculaTitulo;
    private javax.swing.JLabel lblMensajeEstudiantes;
    private javax.swing.JLabel lblMensajeMatricula;
    private javax.swing.JLabel lblMensajeProfesor;
    private javax.swing.JLabel lblNombreEstudiante;
    private javax.swing.JLabel lblNombreProfesor;
    private javax.swing.JLabel lblProfesoresTitulo;
    private javax.swing.JTabbedPane tabMatricula;
    private javax.swing.JTextField txtApellidoEstudiantes;
    private javax.swing.JTextField txtApellidoProfesor;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFacultad;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtNombreProfesor;
    // End of variables declaration//GEN-END:variables
}
