/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herencia;

import java.util.ArrayList;
//import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ESFOT
 */
public class VentanaHerencia extends javax.swing.JFrame {

    ArrayList <Materia> Materias = new ArrayList();
    ArrayList <Profesor> Profesores = new ArrayList();
    ArrayList <Estudiante> Estudiantes = new ArrayList();
    ArrayList<MatriculaEfectuada> Matricula = new ArrayList();
   
   
    public VentanaHerencia() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        lblAviso = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        ComboMateria = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloProfesor = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        lblApellid = new javax.swing.JLabel();
        txtApellidoProfesor = new javax.swing.JTextField();
        lblFacultad = new javax.swing.JLabel();
        txtFacultad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ComboMateriasDisponibles = new javax.swing.JComboBox<>();
        btnRegistrarProfesor = new javax.swing.JButton();
        lblMensajeProfesor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTituloEstudiante = new javax.swing.JLabel();
        lblNombreEstudiantes = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellidoEstudiante = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdadEstudiantes = new javax.swing.JTextField();
        btnRegistrarEstudiantes = new javax.swing.JButton();
        lblMensajeEstudiantes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTituloMaterias = new javax.swing.JLabel();
        lblEstudiantes = new javax.swing.JLabel();
        ComboEstudiantes = new javax.swing.JComboBox<>();
        lblMaterias = new javax.swing.JLabel();
        ComboMateriaFinal = new javax.swing.JComboBox<>();
        btnMatricular = new javax.swing.JButton();
        lblMensajeMatricula = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("REGISTRO DE MATERIAS");

        lblMateria.setText("MATERIA");

        txtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriaActionPerformed(evt);
            }
        });

        lblAviso.setMinimumSize(new java.awt.Dimension(200, 400));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        ComboMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAS" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblMateria)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTitulo)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtMateria))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateria)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Materia", jPanel1);

        lblTituloProfesor.setText("REGISTRO DEL PROFESOR");

        lblNombre.setText("Nombre:");

        lblApellid.setText("Apellido:");

        txtApellidoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoProfesorActionPerformed(evt);
            }
        });

        lblFacultad.setText("Facultad:");

        jLabel1.setText("Materia:");

        ComboMateriasDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAS" }));

        btnRegistrarProfesor.setText("REGISTRAR");
        btnRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblTituloProfesor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellid)
                            .addComponent(lblFacultad)
                            .addComponent(jLabel1))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtApellidoProfesor)
                            .addComponent(txtFacultad)
                            .addComponent(ComboMateriasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnRegistrarProfesor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblMensajeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTituloProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellid)
                    .addComponent(txtApellidoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFacultad)
                    .addComponent(txtFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensajeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboMateriasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnRegistrarProfesor)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Profesor", jPanel2);

        lblTituloEstudiante.setText("REGISTRO DE ESTUDIANTES");

        lblNombreEstudiantes.setText("NOMBRE:");

        lblApellido.setText("APELLIDO:");

        lblEdad.setText("EDAD:");

        btnRegistrarEstudiantes.setText("REGISTRAR");
        btnRegistrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblTituloEstudiante))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEstudiantes)
                            .addComponent(lblApellido)
                            .addComponent(lblEdad))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtApellidoEstudiante)
                            .addComponent(txtEdadEstudiantes)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblMensajeEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnRegistrarEstudiantes)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloEstudiante)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEstudiantes)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellidoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdadEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblMensajeEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarEstudiantes)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiante", jPanel3);

        lblTituloMaterias.setText("LEGALIZACION DE MATRICULA");

        lblEstudiantes.setText("ESTUDIANTES:");

        ComboEstudiantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTES" }));

        lblMaterias.setText("MATERIAS:");

        ComboMateriaFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIAS" }));
        ComboMateriaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMateriaFinalActionPerformed(evt);
            }
        });

        btnMatricular.setText("MATRICULAR");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblTituloMaterias))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstudiantes)
                            .addComponent(lblMaterias))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboMateriaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnMatricular))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblMensajeMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMaterias)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstudiantes)
                    .addComponent(ComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaterias)
                    .addComponent(ComboMateriaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(lblMensajeMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMatricular)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Matricula", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoProfesorActionPerformed

    private void txtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMateriaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       String ingreso=txtMateria.getText();
       Materia comparacionM = new Materia(ingreso);
       boolean existeM= false;
       
       for (Materia item:Materias ){ 
           if(item.getNombre().equals(comparacionM.getNombre())){ 
                  existeM=true;
              JOptionPane.showMessageDialog(rootPane,"Ya existe esta materia");
              lblMensaje.setText("");
              txtMateria.setText("");
              break;
           }
       } 
       if(existeM==false){
        ComboMateria.insertItemAt(txtMateria.getText(),1);
        ComboMateriasDisponibles.insertItemAt(txtMateria.getText(),1);
       
        Materias.add(comparacionM);
        lblMensaje.setText("Materia Ingresada");
       }
     
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfesorActionPerformed
        String nombreProfesor=txtNombreProfesor.getText();
        String apellidoProfesor=txtApellidoProfesor.getText();
        String nombreFacultad=txtFacultad.getText();
        String materiaProfesor= (String)ComboMateriasDisponibles.getSelectedItem();
        
        Profesor comparacionP = new Profesor(nombreProfesor,apellidoProfesor,nombreFacultad,materiaProfesor);
        boolean existeP=false;
        for(Profesor item: Profesores){ 
            if(item.getNombre().equals(comparacionP.getNombre())&& item.getApellido().equals(comparacionP.getApellido())){
             existeP=true;
             JOptionPane.showMessageDialog(rootPane, "Ya existe este Profesor");
             txtNombreProfesor.setText("");
             txtApellidoProfesor.setText("");
             txtFacultad.setText("");
             
            }
        } 
        
        for(Profesor item: Profesores){ 
            if(item.getMateria().equals(comparacionP.getMateria())){
             existeP=true;
             JOptionPane.showMessageDialog(rootPane, "Esta materia ya tiene Profesor");
            }
        } 
        
        if(existeP==false){ 
            Profesores.add(comparacionP);
            lblMensajeProfesor.setText("Profesor registrado");
            ComboMateriaFinal.insertItemAt(txtMateria.getText(),1);
            System.out.println(""+comparacionP);
        }
         
        
       
    }//GEN-LAST:event_btnRegistrarProfesorActionPerformed

    private void ComboMateriaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMateriaFinalActionPerformed
        
    }//GEN-LAST:event_ComboMateriaFinalActionPerformed

    private void btnRegistrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstudiantesActionPerformed
        String nombreEstudiante = txtNombreEstudiante.getText();
        String apellidoEstudiante = txtApellidoEstudiante.getText();
        String edadEstudiante = txtEdadEstudiantes.getText(); 
        Estudiante comparacionE = new Estudiante (nombreEstudiante,apellidoEstudiante,edadEstudiante);
        boolean existeE = false;
        for(Estudiante item: Estudiantes){ 
            if(item.getNombre().equals(comparacionE.getNombre())&& item.getApellido().equals(comparacionE.getApellido())){
                existeE=true;
             JOptionPane.showMessageDialog(rootPane, "Ya existe este Estudiante");
             txtNombreEstudiante.setText("");
             txtApellidoEstudiante.setText("");
             txtEdadEstudiantes.setText(""); 
            }
        
        } 
        
        if(existeE == false){ 
            Estudiantes.add(comparacionE);
            lblMensajeEstudiantes.setText("Estudiante registrado");
            ComboEstudiantes.insertItemAt(txtNombreEstudiante.getText(),1);
        }
    }//GEN-LAST:event_btnRegistrarEstudiantesActionPerformed

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
        String EstudianteSeleccionado= (String)ComboEstudiantes.getSelectedItem();
        String MateriaSeleccionada = (String) ComboMateriaFinal.getSelectedItem(); 
        
        MatriculaEfectuada comparacionMe = new MatriculaEfectuada (EstudianteSeleccionado,MateriaSeleccionada);   
        boolean existeMe=false;
        
        for(MatriculaEfectuada item: Matricula){ 
            if(item.getNombre().equals(comparacionMe.getNombre())&& item.getMateria().equals(comparacionMe.getMateria())){
             existeMe=true;
             JOptionPane.showMessageDialog(rootPane,"Este estudiante ya se matriculo en esta materia");
            }     
        }
        if(existeMe==false){ 
        Matricula.add(comparacionMe);
        lblMensajeMatricula.setText("Estudiante: "+txtNombreEstudiante.getText()+" matriculado");
        }
    }//GEN-LAST:event_btnMatricularActionPerformed
        
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEstudiantes;
    private javax.swing.JComboBox<String> ComboMateria;
    private javax.swing.JComboBox<String> ComboMateriaFinal;
    private javax.swing.JComboBox<String> ComboMateriasDisponibles;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarEstudiantes;
    private javax.swing.JButton btnRegistrarProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblApellid;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstudiantes;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensajeEstudiantes;
    private javax.swing.JLabel lblMensajeMatricula;
    private javax.swing.JLabel lblMensajeProfesor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEstudiantes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloEstudiante;
    private javax.swing.JLabel lblTituloMaterias;
    private javax.swing.JLabel lblTituloProfesor;
    private javax.swing.JTextField txtApellidoEstudiante;
    private javax.swing.JTextField txtApellidoProfesor;
    private javax.swing.JTextField txtEdadEstudiantes;
    private javax.swing.JTextField txtFacultad;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtNombreProfesor;
    // End of variables declaration//GEN-END:variables
}
